openapi: 3.0.3
info:
  title: TRW Project API
  version: 1.0.0
  description: Documentation for TRW Authentication & User Management
paths:
  /api/accounts/2fa/toggle/:
    post:
      operationId: accounts_2fa_toggle_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TwoFAToggle'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TwoFAToggle'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TwoFAToggle'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/accounts/google/:
    post:
      operationId: accounts_google_create
      tags:
      - accounts
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/accounts/login/:
    post:
      operationId: accounts_login_create
      description: ورود با استفاده از ایمیل یا شماره موبایل
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/accounts/logout/:
    post:
      operationId: accounts_logout_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Logout'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Logout'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Logout'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/accounts/password/reset/confirm/:
    post:
      operationId: accounts_password_reset_confirm_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetConfirm'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PasswordResetConfirm'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PasswordResetConfirm'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/accounts/password/reset/request/:
    post:
      operationId: accounts_password_reset_request_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PasswordResetRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PasswordResetRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/accounts/register/:
    post:
      operationId: accounts_register_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/accounts/resend/:
    post:
      operationId: accounts_resend_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OTPResend'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OTPResend'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OTPResend'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/accounts/verify/:
    post:
      operationId: accounts_verify_create
      description: Verify OTP and issue JWT tokens (used for login/register/reset)
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OTPVerify'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OTPVerify'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OTPVerify'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    Login:
      type: object
      properties:
        identifier:
          type: string
          title: E-Mail-Adresse oder Mobilnummer
        password:
          type: string
          writeOnly: true
      required:
      - identifier
      - password
    Logout:
      type: object
      properties:
        refresh:
          type: string
      required:
      - refresh
    OTPResend:
      type: object
      properties:
        otp_id:
          type: string
          format: uuid
      required:
      - otp_id
    OTPVerify:
      type: object
      properties:
        otp_id:
          type: string
          format: uuid
        code:
          type: string
          maxLength: 6
          minLength: 6
      required:
      - code
      - otp_id
    PasswordResetConfirm:
      type: object
      properties:
        otp_id:
          type: string
          format: uuid
        code:
          type: string
          maxLength: 6
          minLength: 6
        new_password:
          type: string
          writeOnly: true
          minLength: 8
        new_password2:
          type: string
          writeOnly: true
          minLength: 8
      required:
      - code
      - new_password
      - new_password2
      - otp_id
    PasswordResetRequest:
      type: object
      properties:
        identifier:
          type: string
      required:
      - identifier
    Register:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        phone_number:
          type: string
          maxLength: 15
        date_of_birth:
          type: string
          format: date
          nullable: true
        password:
          type: string
          writeOnly: true
        password_confirm:
          type: string
          writeOnly: true
        require_otp:
          type: boolean
          writeOnly: true
          default: true
      required:
      - email
      - password
      - password_confirm
      - phone_number
    TwoFAToggle:
      type: object
      properties:
        enabled:
          type: boolean
      required:
      - enabled
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 254
        phone_number:
          type: string
          maxLength: 15
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        date_of_birth:
          type: string
          format: date
          nullable: true
        is_2fa_enabled:
          type: boolean
      required:
      - email
      - id
      - phone_number
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
